// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLoanRequest = "loan_request"

// LoanRequest mapped from table <loan_request>
type LoanRequest struct {
	ID             int32     `gorm:"column:id;primaryKey" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Surname        string    `gorm:"column:surname;not null" json:"surname"`
	Patron         string    `gorm:"column:patron;not null" json:"patron"`
	Phone          string    `gorm:"column:phone;not null" json:"phone"`
	Birth          time.Time `gorm:"column:birth;not null" json:"birth"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	DepartmentCode int32     `gorm:"column:department_code;not null" json:"department_code"`
	IssueDate      time.Time `gorm:"column:issue_date;not null" json:"issue_date"`
	AddedAt        time.Time `gorm:"column:added_at;not null" json:"added_at"`
	PassportSeries int32     `gorm:"column:passport_series;not null" json:"passport_series"`
	PassportNumber int32     `gorm:"column:passport_number;not null" json:"passport_number"`
	Department     string    `gorm:"column:department;not null" json:"department"`
	BirthPlace     string    `gorm:"column:birth_place;not null" json:"birth_place"`
	RegPlace       string    `gorm:"column:reg_place;not null" json:"reg_place"`
}

// TableName LoanRequest's table name
func (*LoanRequest) TableName() string {
	return TableNameLoanRequest
}
