// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOffer = "offer"

// Offer mapped from table <offer>
type Offer struct {
	ID                int32     `gorm:"column:id;primaryKey" json:"id"`
	Name              string    `gorm:"column:name;not null" json:"name"`
	AddedAt           time.Time `gorm:"column:added_at;not null" json:"added_at"`
	IsActive          bool      `gorm:"column:is_active;not null" json:"is_active"`
	Logo              string    `gorm:"column:logo;not null" json:"logo"`
	MaxLoanAmount     int32     `gorm:"column:max_loan_amount;not null" json:"max_loan_amount"`
	InterestRate      float64   `gorm:"column:interest_rate;not null" json:"interest_rate"`
	MinLoanPeriodDays int32     `gorm:"column:min_loan_period_days;not null" json:"min_loan_period_days"`
	MaxLoanPeriodDays int32     `gorm:"column:max_loan_period_days;not null" json:"max_loan_period_days"`
	URL               string    `gorm:"column:url;not null" json:"url"`
	Priority          int32     `gorm:"column:priority;not null" json:"priority"`
}

// TableName Offer's table name
func (*Offer) TableName() string {
	return TableNameOffer
}
