// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePhoneVerifyJob = "phone_verify_job"

// PhoneVerifyJob mapped from table <phone_verify_job>
type PhoneVerifyJob struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	SessionID  string    `gorm:"column:session_id;not null" json:"session_id"`
	Phone      string    `gorm:"column:phone;not null" json:"phone"`
	AddedAt    time.Time `gorm:"column:added_at;not null" json:"added_at"`
	IsActive   bool      `gorm:"column:is_active;not null" json:"is_active"`
	Code       int32     `gorm:"column:code" json:"code"`
	IsVerified bool      `gorm:"column:is_verified;not null" json:"is_verified"`
}

// TableName PhoneVerifyJob's table name
func (*PhoneVerifyJob) TableName() string {
	return TableNamePhoneVerifyJob
}
