// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePush = "push"

// Push mapped from table <push>
type Push struct {
	ID            int32     `gorm:"column:id;primaryKey" json:"id"`
	AddedAt       time.Time `gorm:"column:added_at;not null" json:"added_at"`
	URI           string    `gorm:"column:uri;not null" json:"uri"`
	Target        string    `gorm:"column:target;not null" json:"target"`
	Text          string    `gorm:"column:text;not null" json:"text"`
	ShowDelaySecs int32     `gorm:"column:show_delay_secs;not null" json:"show_delay_secs"`
	IsActive      bool      `gorm:"column:is_active;not null" json:"is_active"`
}

// TableName Push's table name
func (*Push) TableName() string {
	return TableNamePush
}
