// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSm = "sms"

// Sm mapped from table <sms>
type Sm struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	JobID      int32     `gorm:"column:job_id;not null" json:"job_id"`
	SmsQueueID int32     `gorm:"column:sms_queue_id;not null" json:"sms_queue_id"`
	AddedAt    time.Time `gorm:"column:added_at;not null" json:"added_at"`
	Message    string    `gorm:"column:message;not null" json:"message"`
}

// TableName Sm's table name
func (*Sm) TableName() string {
	return TableNameSm
}
