// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsQueue = "sms_queue"

// SmsQueue mapped from table <sms_queue>
type SmsQueue struct {
	ID       int32     `gorm:"column:id;primaryKey" json:"id"`
	AddedAt  time.Time `gorm:"column:added_at;not null" json:"added_at"`
	Status   string    `gorm:"column:status;not null" json:"status"`
	FilePath string    `gorm:"column:file_path" json:"file_path"`
}

// TableName SmsQueue's table name
func (*SmsQueue) TableName() string {
	return TableNameSmsQueue
}
