// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAccess = "user_access"

// UserAccess mapped from table <user_access>
type UserAccess struct {
	ID      int32     `gorm:"column:id;primaryKey" json:"id"`
	IP      string    `gorm:"column:ip;not null" json:"ip"`
	AddedAt time.Time `gorm:"column:added_at;not null" json:"added_at"`
	Limit_  int32     `gorm:"column:_limit;not null" json:"_limit"`
}

// TableName UserAccess's table name
func (*UserAccess) TableName() string {
	return TableNameUserAccess
}
